using System.Text.Json;
using System.Text.Json.Serialization;
using SPTarkov.Server.Core.Models.Utils;

namespace RaidRecovery.Server.Models;

/// <summary>
/// Snapshot of a raid in progress, as sent by the client plugin and written to disk.
/// The server only reads the header; player, world and bots are kept as they are.
/// </summary>
public record Snapshot : IRequestData
{
    /// <summary>Most recent format version this server can read.</summary>
    public const int CurrentVersion = 1;

    [JsonPropertyName("version")]
    public int Version { get; init; }

    [JsonPropertyName("profileId")]
    public string? ProfileId { get; init; }

    /// <summary>Raid identifier, generated by the client at the start of the raid.</summary>
    [JsonPropertyName("sessionId")]
    public string? SessionId { get; init; }

    [JsonPropertyName("map")]
    public string? Map { get; init; }

    [JsonPropertyName("savedAt")]
    public DateTimeOffset? SavedAt { get; init; }

    [JsonPropertyName("raid")]
    public RaidInfo? Raid { get; init; }

    [JsonPropertyName("player")]
    public PlayerState? Player { get; init; }

    [JsonPropertyName("world")]
    public JsonElement? World { get; init; }

    [JsonPropertyName("bots")]
    public JsonElement? Bots { get; init; }
}

public record PlayerState
{
    [JsonPropertyName("position")]
    public Position? Position { get; init; }

    [JsonPropertyName("rotation")]
    public Rotation? Rotation { get; init; }

    /// <summary>
    /// Inventory and health, in the format the game itself sends at the end of a raid.
    /// Kept as is: only SPT knows how to read it, at recovery time.
    /// </summary>
    [JsonPropertyName("profile")]
    public JsonElement? Profile { get; init; }
}

public record Position
{
    [JsonPropertyName("x")]
    public float X { get; init; }

    [JsonPropertyName("y")]
    public float Y { get; init; }

    [JsonPropertyName("z")]
    public float Z { get; init; }
}

public record Rotation
{
    [JsonPropertyName("yaw")]
    public float Yaw { get; init; }

    [JsonPropertyName("pitch")]
    public float Pitch { get; init; }
}

public record RaidInfo
{
    [JsonPropertyName("startedAt")]
    public DateTimeOffset? StartedAt { get; init; }

    /// <summary>Time slot chosen at raid launch: CURR (current time) or PAST (shifted by 12 h).</summary>
    [JsonPropertyName("dateTime")]
    public string? DateTime { get; init; }

    [JsonPropertyName("secondsLeft")]
    public int? SecondsLeft { get; init; }

    [JsonPropertyName("gameTime")]
    public string? GameTime { get; init; }

    [JsonPropertyName("weather")]
    public JsonElement? Weather { get; init; }

    [JsonPropertyName("side")]
    public string? Side { get; init; }
}
